benchmarks:
  - name: disk-4k
    app: fio
    jsonpathInputSelector: "spec.blocks.*.name"
    output: "jobs.*.read.io_bytes"
    resources:
      cpu: "8"
    args:
      - '--rw=randread'
      - '--name=IOPS-randread'
      - '--size=4096'
      - '--bs=4k'
      - '--numjobs=4'
      - '--iodepth=32 '
      - '--refill_buffers'
      - '--group_reporting'
      - '--runtime=30'
      - '--time_based'
      - '--filename={{ inputSelector }}'

  - name: disk-1024k
    app: fio
    jsonpathInputSelector: "spec.blocks.*.name"
    output: "jobs.*.read.io_bytes"
    resources:
      cpu: "8"
    args:
      - '--rw=randread'
      - '--name=IOPS-randread'
      - '--size=4096'
      - '--bs=1024k'
      - '--numjobs=4'
      - '--iodepth=32 '
      - '--refill_buffers'
      - '--group_reporting'
      - '--runtime=30'
      - '--time_based'
      - '--filename={{ inputSelector }}'